// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserManagement/Users.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Shared.Contracts.UserManagement.Users {
  public static partial class UsersService
  {
    static readonly string __ServiceName = "Shared.Contracts.UserManagement.Users.UsersService";

    static readonly grpc::Marshaller<global::Shared.Contracts.UserManagement.Users.GetUserByUsernameParameter> __Marshaller_Shared_Contracts_UserManagement_Users_GetUserByUsernameParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.UserManagement.Users.GetUserByUsernameParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.UserManagement.Users.GetUserByUsernameResult> __Marshaller_Shared_Contracts_UserManagement_Users_GetUserByUsernameResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.UserManagement.Users.GetUserByUsernameResult.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.UserManagement.Users.RegisterUserParameter> __Marshaller_Shared_Contracts_UserManagement_Users_RegisterUserParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.UserManagement.Users.RegisterUserParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.Common.Empty> __Marshaller_Shared_Contracts_Common_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.Common.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.UserManagement.Users.AuthenticateUserParameter> __Marshaller_Shared_Contracts_UserManagement_Users_AuthenticateUserParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.UserManagement.Users.AuthenticateUserParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.UserManagement.Users.AuthenticateUserResult> __Marshaller_Shared_Contracts_UserManagement_Users_AuthenticateUserResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.UserManagement.Users.AuthenticateUserResult.Parser.ParseFrom);

    static readonly grpc::Method<global::Shared.Contracts.UserManagement.Users.GetUserByUsernameParameter, global::Shared.Contracts.UserManagement.Users.GetUserByUsernameResult> __Method_GetUserByUsername = new grpc::Method<global::Shared.Contracts.UserManagement.Users.GetUserByUsernameParameter, global::Shared.Contracts.UserManagement.Users.GetUserByUsernameResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUserByUsername",
        __Marshaller_Shared_Contracts_UserManagement_Users_GetUserByUsernameParameter,
        __Marshaller_Shared_Contracts_UserManagement_Users_GetUserByUsernameResult);

    static readonly grpc::Method<global::Shared.Contracts.UserManagement.Users.RegisterUserParameter, global::Shared.Contracts.Common.Empty> __Method_RegisterUser = new grpc::Method<global::Shared.Contracts.UserManagement.Users.RegisterUserParameter, global::Shared.Contracts.Common.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RegisterUser",
        __Marshaller_Shared_Contracts_UserManagement_Users_RegisterUserParameter,
        __Marshaller_Shared_Contracts_Common_Empty);

    static readonly grpc::Method<global::Shared.Contracts.UserManagement.Users.AuthenticateUserParameter, global::Shared.Contracts.UserManagement.Users.AuthenticateUserResult> __Method_AuthenticateUser = new grpc::Method<global::Shared.Contracts.UserManagement.Users.AuthenticateUserParameter, global::Shared.Contracts.UserManagement.Users.AuthenticateUserResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AuthenticateUser",
        __Marshaller_Shared_Contracts_UserManagement_Users_AuthenticateUserParameter,
        __Marshaller_Shared_Contracts_UserManagement_Users_AuthenticateUserResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Shared.Contracts.UserManagement.Users.UsersReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UsersService</summary>
    public abstract partial class UsersServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.UserManagement.Users.GetUserByUsernameResult> GetUserByUsername(global::Shared.Contracts.UserManagement.Users.GetUserByUsernameParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.Common.Empty> RegisterUser(global::Shared.Contracts.UserManagement.Users.RegisterUserParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.UserManagement.Users.AuthenticateUserResult> AuthenticateUser(global::Shared.Contracts.UserManagement.Users.AuthenticateUserParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UsersService</summary>
    public partial class UsersServiceClient : grpc::ClientBase<UsersServiceClient>
    {
      /// <summary>Creates a new client for UsersService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UsersServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UsersService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UsersServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UsersServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UsersServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Shared.Contracts.UserManagement.Users.GetUserByUsernameResult GetUserByUsername(global::Shared.Contracts.UserManagement.Users.GetUserByUsernameParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUserByUsername(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.UserManagement.Users.GetUserByUsernameResult GetUserByUsername(global::Shared.Contracts.UserManagement.Users.GetUserByUsernameParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUserByUsername, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.UserManagement.Users.GetUserByUsernameResult> GetUserByUsernameAsync(global::Shared.Contracts.UserManagement.Users.GetUserByUsernameParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUserByUsernameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.UserManagement.Users.GetUserByUsernameResult> GetUserByUsernameAsync(global::Shared.Contracts.UserManagement.Users.GetUserByUsernameParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUserByUsername, null, options, request);
      }
      public virtual global::Shared.Contracts.Common.Empty RegisterUser(global::Shared.Contracts.UserManagement.Users.RegisterUserParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegisterUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.Common.Empty RegisterUser(global::Shared.Contracts.UserManagement.Users.RegisterUserParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RegisterUser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.Common.Empty> RegisterUserAsync(global::Shared.Contracts.UserManagement.Users.RegisterUserParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegisterUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.Common.Empty> RegisterUserAsync(global::Shared.Contracts.UserManagement.Users.RegisterUserParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RegisterUser, null, options, request);
      }
      public virtual global::Shared.Contracts.UserManagement.Users.AuthenticateUserResult AuthenticateUser(global::Shared.Contracts.UserManagement.Users.AuthenticateUserParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AuthenticateUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.UserManagement.Users.AuthenticateUserResult AuthenticateUser(global::Shared.Contracts.UserManagement.Users.AuthenticateUserParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AuthenticateUser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.UserManagement.Users.AuthenticateUserResult> AuthenticateUserAsync(global::Shared.Contracts.UserManagement.Users.AuthenticateUserParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AuthenticateUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.UserManagement.Users.AuthenticateUserResult> AuthenticateUserAsync(global::Shared.Contracts.UserManagement.Users.AuthenticateUserParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AuthenticateUser, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UsersServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UsersServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UsersServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetUserByUsername, serviceImpl.GetUserByUsername)
          .AddMethod(__Method_RegisterUser, serviceImpl.RegisterUser)
          .AddMethod(__Method_AuthenticateUser, serviceImpl.AuthenticateUser).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UsersServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetUserByUsername, serviceImpl.GetUserByUsername);
      serviceBinder.AddMethod(__Method_RegisterUser, serviceImpl.RegisterUser);
      serviceBinder.AddMethod(__Method_AuthenticateUser, serviceImpl.AuthenticateUser);
    }

  }
}
#endregion
