// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QuizManagement/Quizzes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Shared.Contracts.QuizManagement.Quizzes {

  /// <summary>Holder for reflection information generated from QuizManagement/Quizzes.proto</summary>
  public static partial class QuizzesReflection {

    #region Descriptor
    /// <summary>File descriptor for QuizManagement/Quizzes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuizzesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxRdWl6TWFuYWdlbWVudC9RdWl6emVzLnByb3RvEidTaGFyZWQuQ29udHJh",
            "Y3RzLlF1aXpNYW5hZ2VtZW50LlF1aXp6ZXMaE0NvbW1vbi9Db21tb24ucHJv",
            "dG8iJgoUR2V0UXVpekJ5SWRQYXJhbWV0ZXISDgoGUXVpeklkGAEgASgFIm4K",
            "HkdldFF1aXp6ZXNCeVVzZXJQYWdlZFBhcmFtZXRlchI8CghQYWdlSW5mbxgB",
            "IAEoCzIqLlNoYXJlZC5Db250cmFjdHMuQ29tbW9uLkdldFBhZ2VkUGFyYW1l",
            "dGVyEg4KBlVzZXJJZBgCIAEoCSJwCh9HZXRRdWl6emVzQnlUb3BpY1BhZ2Vk",
            "UGFyYW1ldGVyEjwKCFBhZ2VJbmZvGAEgASgLMiouU2hhcmVkLkNvbnRyYWN0",
            "cy5Db21tb24uR2V0UGFnZWRQYXJhbWV0ZXISDwoHVG9waWNJZBgCIAEoBSIl",
            "ChNEZWxldGVRdWl6UGFyYW1ldGVyEg4KBlF1aXpJZBgBIAEoBSJCChxEZWxl",
            "dGVRdWl6emVzQnlVc2VyUGFyYW1ldGVyEg4KBlVzZXJJZBgBIAEoCRISCgpL",
            "ZWVwUHVibGljGAIgASgIIrcBChNDcmVhdGVRdWl6UGFyYW1ldGVyEgwKBE5h",
            "bWUYASABKAkSDgoGVXNlcklkGAIgASgJEk0KCVF1ZXN0aW9ucxgDIAMoCzI6",
            "LlNoYXJlZC5Db250cmFjdHMuUXVpek1hbmFnZW1lbnQuUXVpenplcy5RdWVz",
            "dGlvblBhcmFtZXRlchIPCgdUb3BpY0lkGAQgASgFEhAKCElzUHVibGljGAUg",
            "ASgIEhAKCEltYWdlVXJsGAYgASgJIoYBChFRdWVzdGlvblBhcmFtZXRlchIM",
            "CgRUZXh0GAEgASgJEhgKEElzTXVsdGlwbGVDaG9pY2UYAiABKAgSSQoHQW5z",
            "d2VycxgDIAMoCzI4LlNoYXJlZC5Db250cmFjdHMuUXVpek1hbmFnZW1lbnQu",
            "UXVpenplcy5BbnN3ZXJQYXJhbWV0ZXIiMgoPQW5zd2VyUGFyYW1ldGVyEgwK",
            "BFRleHQYASABKAkSEQoJSXNDb3JyZWN0GAIgASgIIpECChFHZXRRdWl6QnlJ",
            "ZFJlc3VsdBIOCgZRdWl6SWQYASABKAUSDAoETmFtZRgCIAEoCRIZChFDcmVh",
            "dGlvblRpbWVzdGFtcBgDIAEoAxIOCgZVc2VySWQYBCABKAkSSgoJUXVlc3Rp",
            "b25zGAUgAygLMjcuU2hhcmVkLkNvbnRyYWN0cy5RdWl6TWFuYWdlbWVudC5R",
            "dWl6emVzLlF1ZXN0aW9uUmVzdWx0EkMKBVRvcGljGAYgASgLMjQuU2hhcmVk",
            "LkNvbnRyYWN0cy5RdWl6TWFuYWdlbWVudC5RdWl6emVzLlRvcGljUmVzdWx0",
            "EhAKCElzUHVibGljGAcgASgIEhAKCEltYWdlVXJsGAggASgJIpgBChVHZXRR",
            "dWl6emVzUGFnZWRSZXN1bHQSOQoIUGFnZUluZm8YASABKAsyJy5TaGFyZWQu",
            "Q29udHJhY3RzLkNvbW1vbi5HZXRQYWdlZFJlc3VsdBJECgdRdWl6emVzGAIg",
            "AygLMjMuU2hhcmVkLkNvbnRyYWN0cy5RdWl6TWFuYWdlbWVudC5RdWl6emVz",
            "LlF1aXpSZXN1bHQiQQoMQW5zd2VyUmVzdWx0EhAKCEFuc3dlcklkGAEgASgF",
            "EgwKBFRleHQYAiABKAkSEQoJSXNDb3JyZWN0GAMgASgIIpQBCg5RdWVzdGlv",
            "blJlc3VsdBISCgpRdWVzdGlvbklkGAEgASgFEgwKBFRleHQYAiABKAkSGAoQ",
            "SXNNdWx0aXBsZUNob2ljZRgDIAEoCBJGCgdBbnN3ZXJzGAQgAygLMjUuU2hh",
            "cmVkLkNvbnRyYWN0cy5RdWl6TWFuYWdlbWVudC5RdWl6emVzLkFuc3dlclJl",
            "c3VsdCK+AQoKUXVpelJlc3VsdBIOCgZRdWl6SWQYASABKAUSDAoETmFtZRgC",
            "IAEoCRIZChFDcmVhdGlvblRpbWVzdGFtcBgDIAEoAxIOCgZVc2VySWQYBCAB",
            "KAkSQwoFVG9waWMYBSABKAsyNC5TaGFyZWQuQ29udHJhY3RzLlF1aXpNYW5h",
            "Z2VtZW50LlF1aXp6ZXMuVG9waWNSZXN1bHQSEAoISXNQdWJsaWMYBiABKAgS",
            "EAoISW1hZ2VVcmwYByABKAkiPgoLVG9waWNSZXN1bHQSDwoHVG9waWNJZBgB",
            "IAEoBRIMCgROYW1lGAIgASgJEhAKCEltYWdlVXJsGAMgASgJMt0ICg5RdWl6",
            "emVzU2VydmljZRJ9Cg9HZXRRdWl6emVzUGFnZWQSKi5TaGFyZWQuQ29udHJh",
            "Y3RzLkNvbW1vbi5HZXRQYWdlZFBhcmFtZXRlcho+LlNoYXJlZC5Db250cmFj",
            "dHMuUXVpek1hbmFnZW1lbnQuUXVpenplcy5HZXRRdWl6emVzUGFnZWRSZXN1",
            "bHQShAEKB0dldFF1aXoSPS5TaGFyZWQuQ29udHJhY3RzLlF1aXpNYW5hZ2Vt",
            "ZW50LlF1aXp6ZXMuR2V0UXVpekJ5SWRQYXJhbWV0ZXIaOi5TaGFyZWQuQ29u",
            "dHJhY3RzLlF1aXpNYW5hZ2VtZW50LlF1aXp6ZXMuR2V0UXVpekJ5SWRSZXN1",
            "bHQSoAEKFUdldFF1aXp6ZXNCeVVzZXJQYWdlZBJHLlNoYXJlZC5Db250cmFj",
            "dHMuUXVpek1hbmFnZW1lbnQuUXVpenplcy5HZXRRdWl6emVzQnlVc2VyUGFn",
            "ZWRQYXJhbWV0ZXIaPi5TaGFyZWQuQ29udHJhY3RzLlF1aXpNYW5hZ2VtZW50",
            "LlF1aXp6ZXMuR2V0UXVpenplc1BhZ2VkUmVzdWx0EqYBChtHZXRQdWJsaWNR",
            "dWl6emVzQnlVc2VyUGFnZWQSRy5TaGFyZWQuQ29udHJhY3RzLlF1aXpNYW5h",
            "Z2VtZW50LlF1aXp6ZXMuR2V0UXVpenplc0J5VXNlclBhZ2VkUGFyYW1ldGVy",
            "Gj4uU2hhcmVkLkNvbnRyYWN0cy5RdWl6TWFuYWdlbWVudC5RdWl6emVzLkdl",
            "dFF1aXp6ZXNQYWdlZFJlc3VsdBKiAQoWR2V0UXVpenplc0J5VG9waWNQYWdl",
            "ZBJILlNoYXJlZC5Db250cmFjdHMuUXVpek1hbmFnZW1lbnQuUXVpenplcy5H",
            "ZXRRdWl6emVzQnlUb3BpY1BhZ2VkUGFyYW1ldGVyGj4uU2hhcmVkLkNvbnRy",
            "YWN0cy5RdWl6TWFuYWdlbWVudC5RdWl6emVzLkdldFF1aXp6ZXNQYWdlZFJl",
            "c3VsdBJqCgpDcmVhdGVRdWl6EjwuU2hhcmVkLkNvbnRyYWN0cy5RdWl6TWFu",
            "YWdlbWVudC5RdWl6emVzLkNyZWF0ZVF1aXpQYXJhbWV0ZXIaHi5TaGFyZWQu",
            "Q29udHJhY3RzLkNvbW1vbi5FbXB0eRJqCgpEZWxldGVRdWl6EjwuU2hhcmVk",
            "LkNvbnRyYWN0cy5RdWl6TWFuYWdlbWVudC5RdWl6emVzLkRlbGV0ZVF1aXpQ",
            "YXJhbWV0ZXIaHi5TaGFyZWQuQ29udHJhY3RzLkNvbW1vbi5FbXB0eRJ8ChNE",
            "ZWxldGVRdWl6emVzQnlVc2VyEkUuU2hhcmVkLkNvbnRyYWN0cy5RdWl6TWFu",
            "YWdlbWVudC5RdWl6emVzLkRlbGV0ZVF1aXp6ZXNCeVVzZXJQYXJhbWV0ZXIa",
            "Hi5TaGFyZWQuQ29udHJhY3RzLkNvbW1vbi5FbXB0eWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Shared.Contracts.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter.Parser, new[]{ "QuizId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter.Parser, new[]{ "PageInfo", "UserId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter.Parser, new[]{ "PageInfo", "TopicId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter), global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter.Parser, new[]{ "QuizId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter), global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter.Parser, new[]{ "UserId", "KeepPublic" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter), global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter.Parser, new[]{ "Name", "UserId", "Questions", "TopicId", "IsPublic", "ImageUrl" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.QuestionParameter), global::Shared.Contracts.QuizManagement.Quizzes.QuestionParameter.Parser, new[]{ "Text", "IsMultipleChoice", "Answers" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.AnswerParameter), global::Shared.Contracts.QuizManagement.Quizzes.AnswerParameter.Parser, new[]{ "Text", "IsCorrect" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult.Parser, new[]{ "QuizId", "Name", "CreationTimestamp", "UserId", "Questions", "Topic", "IsPublic", "ImageUrl" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult.Parser, new[]{ "PageInfo", "Quizzes" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.AnswerResult), global::Shared.Contracts.QuizManagement.Quizzes.AnswerResult.Parser, new[]{ "AnswerId", "Text", "IsCorrect" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.QuestionResult), global::Shared.Contracts.QuizManagement.Quizzes.QuestionResult.Parser, new[]{ "QuestionId", "Text", "IsMultipleChoice", "Answers" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.QuizResult), global::Shared.Contracts.QuizManagement.Quizzes.QuizResult.Parser, new[]{ "QuizId", "Name", "CreationTimestamp", "UserId", "Topic", "IsPublic", "ImageUrl" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Shared.Contracts.QuizManagement.Quizzes.TopicResult), global::Shared.Contracts.QuizManagement.Quizzes.TopicResult.Parser, new[]{ "TopicId", "Name", "ImageUrl" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetQuizByIdParameter : pb::IMessage<GetQuizByIdParameter> {
    private static readonly pb::MessageParser<GetQuizByIdParameter> _parser = new pb::MessageParser<GetQuizByIdParameter>(() => new GetQuizByIdParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetQuizByIdParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizByIdParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizByIdParameter(GetQuizByIdParameter other) : this() {
      quizId_ = other.quizId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizByIdParameter Clone() {
      return new GetQuizByIdParameter(this);
    }

    /// <summary>Field number for the "QuizId" field.</summary>
    public const int QuizIdFieldNumber = 1;
    private int quizId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int QuizId {
      get { return quizId_; }
      set {
        quizId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetQuizByIdParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetQuizByIdParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QuizId != other.QuizId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (QuizId != 0) hash ^= QuizId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (QuizId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QuizId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (QuizId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuizId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetQuizByIdParameter other) {
      if (other == null) {
        return;
      }
      if (other.QuizId != 0) {
        QuizId = other.QuizId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            QuizId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetQuizzesByUserPagedParameter : pb::IMessage<GetQuizzesByUserPagedParameter> {
    private static readonly pb::MessageParser<GetQuizzesByUserPagedParameter> _parser = new pb::MessageParser<GetQuizzesByUserPagedParameter>(() => new GetQuizzesByUserPagedParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetQuizzesByUserPagedParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizzesByUserPagedParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizzesByUserPagedParameter(GetQuizzesByUserPagedParameter other) : this() {
      pageInfo_ = other.pageInfo_ != null ? other.pageInfo_.Clone() : null;
      userId_ = other.userId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizzesByUserPagedParameter Clone() {
      return new GetQuizzesByUserPagedParameter(this);
    }

    /// <summary>Field number for the "PageInfo" field.</summary>
    public const int PageInfoFieldNumber = 1;
    private global::Shared.Contracts.Common.GetPagedParameter pageInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Shared.Contracts.Common.GetPagedParameter PageInfo {
      get { return pageInfo_; }
      set {
        pageInfo_ = value;
      }
    }

    /// <summary>Field number for the "UserId" field.</summary>
    public const int UserIdFieldNumber = 2;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetQuizzesByUserPagedParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetQuizzesByUserPagedParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PageInfo, other.PageInfo)) return false;
      if (UserId != other.UserId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (pageInfo_ != null) hash ^= PageInfo.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (pageInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PageInfo);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (pageInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PageInfo);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetQuizzesByUserPagedParameter other) {
      if (other == null) {
        return;
      }
      if (other.pageInfo_ != null) {
        if (pageInfo_ == null) {
          PageInfo = new global::Shared.Contracts.Common.GetPagedParameter();
        }
        PageInfo.MergeFrom(other.PageInfo);
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pageInfo_ == null) {
              PageInfo = new global::Shared.Contracts.Common.GetPagedParameter();
            }
            input.ReadMessage(PageInfo);
            break;
          }
          case 18: {
            UserId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetQuizzesByTopicPagedParameter : pb::IMessage<GetQuizzesByTopicPagedParameter> {
    private static readonly pb::MessageParser<GetQuizzesByTopicPagedParameter> _parser = new pb::MessageParser<GetQuizzesByTopicPagedParameter>(() => new GetQuizzesByTopicPagedParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetQuizzesByTopicPagedParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizzesByTopicPagedParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizzesByTopicPagedParameter(GetQuizzesByTopicPagedParameter other) : this() {
      pageInfo_ = other.pageInfo_ != null ? other.pageInfo_.Clone() : null;
      topicId_ = other.topicId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizzesByTopicPagedParameter Clone() {
      return new GetQuizzesByTopicPagedParameter(this);
    }

    /// <summary>Field number for the "PageInfo" field.</summary>
    public const int PageInfoFieldNumber = 1;
    private global::Shared.Contracts.Common.GetPagedParameter pageInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Shared.Contracts.Common.GetPagedParameter PageInfo {
      get { return pageInfo_; }
      set {
        pageInfo_ = value;
      }
    }

    /// <summary>Field number for the "TopicId" field.</summary>
    public const int TopicIdFieldNumber = 2;
    private int topicId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TopicId {
      get { return topicId_; }
      set {
        topicId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetQuizzesByTopicPagedParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetQuizzesByTopicPagedParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PageInfo, other.PageInfo)) return false;
      if (TopicId != other.TopicId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (pageInfo_ != null) hash ^= PageInfo.GetHashCode();
      if (TopicId != 0) hash ^= TopicId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (pageInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PageInfo);
      }
      if (TopicId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TopicId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (pageInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PageInfo);
      }
      if (TopicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopicId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetQuizzesByTopicPagedParameter other) {
      if (other == null) {
        return;
      }
      if (other.pageInfo_ != null) {
        if (pageInfo_ == null) {
          PageInfo = new global::Shared.Contracts.Common.GetPagedParameter();
        }
        PageInfo.MergeFrom(other.PageInfo);
      }
      if (other.TopicId != 0) {
        TopicId = other.TopicId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pageInfo_ == null) {
              PageInfo = new global::Shared.Contracts.Common.GetPagedParameter();
            }
            input.ReadMessage(PageInfo);
            break;
          }
          case 16: {
            TopicId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DeleteQuizParameter : pb::IMessage<DeleteQuizParameter> {
    private static readonly pb::MessageParser<DeleteQuizParameter> _parser = new pb::MessageParser<DeleteQuizParameter>(() => new DeleteQuizParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteQuizParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteQuizParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteQuizParameter(DeleteQuizParameter other) : this() {
      quizId_ = other.quizId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteQuizParameter Clone() {
      return new DeleteQuizParameter(this);
    }

    /// <summary>Field number for the "QuizId" field.</summary>
    public const int QuizIdFieldNumber = 1;
    private int quizId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int QuizId {
      get { return quizId_; }
      set {
        quizId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteQuizParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteQuizParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QuizId != other.QuizId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (QuizId != 0) hash ^= QuizId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (QuizId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QuizId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (QuizId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuizId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteQuizParameter other) {
      if (other == null) {
        return;
      }
      if (other.QuizId != 0) {
        QuizId = other.QuizId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            QuizId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DeleteQuizzesByUserParameter : pb::IMessage<DeleteQuizzesByUserParameter> {
    private static readonly pb::MessageParser<DeleteQuizzesByUserParameter> _parser = new pb::MessageParser<DeleteQuizzesByUserParameter>(() => new DeleteQuizzesByUserParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteQuizzesByUserParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteQuizzesByUserParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteQuizzesByUserParameter(DeleteQuizzesByUserParameter other) : this() {
      userId_ = other.userId_;
      keepPublic_ = other.keepPublic_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteQuizzesByUserParameter Clone() {
      return new DeleteQuizzesByUserParameter(this);
    }

    /// <summary>Field number for the "UserId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "KeepPublic" field.</summary>
    public const int KeepPublicFieldNumber = 2;
    private bool keepPublic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool KeepPublic {
      get { return keepPublic_; }
      set {
        keepPublic_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteQuizzesByUserParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteQuizzesByUserParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (KeepPublic != other.KeepPublic) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (KeepPublic != false) hash ^= KeepPublic.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (KeepPublic != false) {
        output.WriteRawTag(16);
        output.WriteBool(KeepPublic);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (KeepPublic != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteQuizzesByUserParameter other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.KeepPublic != false) {
        KeepPublic = other.KeepPublic;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 16: {
            KeepPublic = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateQuizParameter : pb::IMessage<CreateQuizParameter> {
    private static readonly pb::MessageParser<CreateQuizParameter> _parser = new pb::MessageParser<CreateQuizParameter>(() => new CreateQuizParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateQuizParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateQuizParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateQuizParameter(CreateQuizParameter other) : this() {
      name_ = other.name_;
      userId_ = other.userId_;
      questions_ = other.questions_.Clone();
      topicId_ = other.topicId_;
      isPublic_ = other.isPublic_;
      imageUrl_ = other.imageUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateQuizParameter Clone() {
      return new CreateQuizParameter(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "UserId" field.</summary>
    public const int UserIdFieldNumber = 2;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Questions" field.</summary>
    public const int QuestionsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Shared.Contracts.QuizManagement.Quizzes.QuestionParameter> _repeated_questions_codec
        = pb::FieldCodec.ForMessage(26, global::Shared.Contracts.QuizManagement.Quizzes.QuestionParameter.Parser);
    private readonly pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.QuestionParameter> questions_ = new pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.QuestionParameter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.QuestionParameter> Questions {
      get { return questions_; }
    }

    /// <summary>Field number for the "TopicId" field.</summary>
    public const int TopicIdFieldNumber = 4;
    private int topicId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TopicId {
      get { return topicId_; }
      set {
        topicId_ = value;
      }
    }

    /// <summary>Field number for the "IsPublic" field.</summary>
    public const int IsPublicFieldNumber = 5;
    private bool isPublic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsPublic {
      get { return isPublic_; }
      set {
        isPublic_ = value;
      }
    }

    /// <summary>Field number for the "ImageUrl" field.</summary>
    public const int ImageUrlFieldNumber = 6;
    private string imageUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ImageUrl {
      get { return imageUrl_; }
      set {
        imageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateQuizParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateQuizParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (UserId != other.UserId) return false;
      if(!questions_.Equals(other.questions_)) return false;
      if (TopicId != other.TopicId) return false;
      if (IsPublic != other.IsPublic) return false;
      if (ImageUrl != other.ImageUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      hash ^= questions_.GetHashCode();
      if (TopicId != 0) hash ^= TopicId.GetHashCode();
      if (IsPublic != false) hash ^= IsPublic.GetHashCode();
      if (ImageUrl.Length != 0) hash ^= ImageUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserId);
      }
      questions_.WriteTo(output, _repeated_questions_codec);
      if (TopicId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(TopicId);
      }
      if (IsPublic != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsPublic);
      }
      if (ImageUrl.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ImageUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      size += questions_.CalculateSize(_repeated_questions_codec);
      if (TopicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopicId);
      }
      if (IsPublic != false) {
        size += 1 + 1;
      }
      if (ImageUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateQuizParameter other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      questions_.Add(other.questions_);
      if (other.TopicId != 0) {
        TopicId = other.TopicId;
      }
      if (other.IsPublic != false) {
        IsPublic = other.IsPublic;
      }
      if (other.ImageUrl.Length != 0) {
        ImageUrl = other.ImageUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            UserId = input.ReadString();
            break;
          }
          case 26: {
            questions_.AddEntriesFrom(input, _repeated_questions_codec);
            break;
          }
          case 32: {
            TopicId = input.ReadInt32();
            break;
          }
          case 40: {
            IsPublic = input.ReadBool();
            break;
          }
          case 50: {
            ImageUrl = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class QuestionParameter : pb::IMessage<QuestionParameter> {
    private static readonly pb::MessageParser<QuestionParameter> _parser = new pb::MessageParser<QuestionParameter>(() => new QuestionParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuestionParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuestionParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuestionParameter(QuestionParameter other) : this() {
      text_ = other.text_;
      isMultipleChoice_ = other.isMultipleChoice_;
      answers_ = other.answers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuestionParameter Clone() {
      return new QuestionParameter(this);
    }

    /// <summary>Field number for the "Text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IsMultipleChoice" field.</summary>
    public const int IsMultipleChoiceFieldNumber = 2;
    private bool isMultipleChoice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsMultipleChoice {
      get { return isMultipleChoice_; }
      set {
        isMultipleChoice_ = value;
      }
    }

    /// <summary>Field number for the "Answers" field.</summary>
    public const int AnswersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Shared.Contracts.QuizManagement.Quizzes.AnswerParameter> _repeated_answers_codec
        = pb::FieldCodec.ForMessage(26, global::Shared.Contracts.QuizManagement.Quizzes.AnswerParameter.Parser);
    private readonly pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.AnswerParameter> answers_ = new pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.AnswerParameter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.AnswerParameter> Answers {
      get { return answers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuestionParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuestionParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      if (IsMultipleChoice != other.IsMultipleChoice) return false;
      if(!answers_.Equals(other.answers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (IsMultipleChoice != false) hash ^= IsMultipleChoice.GetHashCode();
      hash ^= answers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (IsMultipleChoice != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsMultipleChoice);
      }
      answers_.WriteTo(output, _repeated_answers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (IsMultipleChoice != false) {
        size += 1 + 1;
      }
      size += answers_.CalculateSize(_repeated_answers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuestionParameter other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      if (other.IsMultipleChoice != false) {
        IsMultipleChoice = other.IsMultipleChoice;
      }
      answers_.Add(other.answers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 16: {
            IsMultipleChoice = input.ReadBool();
            break;
          }
          case 26: {
            answers_.AddEntriesFrom(input, _repeated_answers_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class AnswerParameter : pb::IMessage<AnswerParameter> {
    private static readonly pb::MessageParser<AnswerParameter> _parser = new pb::MessageParser<AnswerParameter>(() => new AnswerParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AnswerParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnswerParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnswerParameter(AnswerParameter other) : this() {
      text_ = other.text_;
      isCorrect_ = other.isCorrect_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnswerParameter Clone() {
      return new AnswerParameter(this);
    }

    /// <summary>Field number for the "Text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IsCorrect" field.</summary>
    public const int IsCorrectFieldNumber = 2;
    private bool isCorrect_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsCorrect {
      get { return isCorrect_; }
      set {
        isCorrect_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AnswerParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AnswerParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      if (IsCorrect != other.IsCorrect) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (IsCorrect != false) hash ^= IsCorrect.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (IsCorrect != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsCorrect);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (IsCorrect != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AnswerParameter other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      if (other.IsCorrect != false) {
        IsCorrect = other.IsCorrect;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 16: {
            IsCorrect = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetQuizByIdResult : pb::IMessage<GetQuizByIdResult> {
    private static readonly pb::MessageParser<GetQuizByIdResult> _parser = new pb::MessageParser<GetQuizByIdResult>(() => new GetQuizByIdResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetQuizByIdResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizByIdResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizByIdResult(GetQuizByIdResult other) : this() {
      quizId_ = other.quizId_;
      name_ = other.name_;
      creationTimestamp_ = other.creationTimestamp_;
      userId_ = other.userId_;
      questions_ = other.questions_.Clone();
      topic_ = other.topic_ != null ? other.topic_.Clone() : null;
      isPublic_ = other.isPublic_;
      imageUrl_ = other.imageUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizByIdResult Clone() {
      return new GetQuizByIdResult(this);
    }

    /// <summary>Field number for the "QuizId" field.</summary>
    public const int QuizIdFieldNumber = 1;
    private int quizId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int QuizId {
      get { return quizId_; }
      set {
        quizId_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CreationTimestamp" field.</summary>
    public const int CreationTimestampFieldNumber = 3;
    private long creationTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CreationTimestamp {
      get { return creationTimestamp_; }
      set {
        creationTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "UserId" field.</summary>
    public const int UserIdFieldNumber = 4;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Questions" field.</summary>
    public const int QuestionsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Shared.Contracts.QuizManagement.Quizzes.QuestionResult> _repeated_questions_codec
        = pb::FieldCodec.ForMessage(42, global::Shared.Contracts.QuizManagement.Quizzes.QuestionResult.Parser);
    private readonly pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.QuestionResult> questions_ = new pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.QuestionResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.QuestionResult> Questions {
      get { return questions_; }
    }

    /// <summary>Field number for the "Topic" field.</summary>
    public const int TopicFieldNumber = 6;
    private global::Shared.Contracts.QuizManagement.Quizzes.TopicResult topic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Shared.Contracts.QuizManagement.Quizzes.TopicResult Topic {
      get { return topic_; }
      set {
        topic_ = value;
      }
    }

    /// <summary>Field number for the "IsPublic" field.</summary>
    public const int IsPublicFieldNumber = 7;
    private bool isPublic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsPublic {
      get { return isPublic_; }
      set {
        isPublic_ = value;
      }
    }

    /// <summary>Field number for the "ImageUrl" field.</summary>
    public const int ImageUrlFieldNumber = 8;
    private string imageUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ImageUrl {
      get { return imageUrl_; }
      set {
        imageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetQuizByIdResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetQuizByIdResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QuizId != other.QuizId) return false;
      if (Name != other.Name) return false;
      if (CreationTimestamp != other.CreationTimestamp) return false;
      if (UserId != other.UserId) return false;
      if(!questions_.Equals(other.questions_)) return false;
      if (!object.Equals(Topic, other.Topic)) return false;
      if (IsPublic != other.IsPublic) return false;
      if (ImageUrl != other.ImageUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (QuizId != 0) hash ^= QuizId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (CreationTimestamp != 0L) hash ^= CreationTimestamp.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      hash ^= questions_.GetHashCode();
      if (topic_ != null) hash ^= Topic.GetHashCode();
      if (IsPublic != false) hash ^= IsPublic.GetHashCode();
      if (ImageUrl.Length != 0) hash ^= ImageUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (QuizId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QuizId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (CreationTimestamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CreationTimestamp);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UserId);
      }
      questions_.WriteTo(output, _repeated_questions_codec);
      if (topic_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Topic);
      }
      if (IsPublic != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsPublic);
      }
      if (ImageUrl.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ImageUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (QuizId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuizId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (CreationTimestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreationTimestamp);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      size += questions_.CalculateSize(_repeated_questions_codec);
      if (topic_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Topic);
      }
      if (IsPublic != false) {
        size += 1 + 1;
      }
      if (ImageUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetQuizByIdResult other) {
      if (other == null) {
        return;
      }
      if (other.QuizId != 0) {
        QuizId = other.QuizId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.CreationTimestamp != 0L) {
        CreationTimestamp = other.CreationTimestamp;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      questions_.Add(other.questions_);
      if (other.topic_ != null) {
        if (topic_ == null) {
          Topic = new global::Shared.Contracts.QuizManagement.Quizzes.TopicResult();
        }
        Topic.MergeFrom(other.Topic);
      }
      if (other.IsPublic != false) {
        IsPublic = other.IsPublic;
      }
      if (other.ImageUrl.Length != 0) {
        ImageUrl = other.ImageUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            QuizId = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            CreationTimestamp = input.ReadInt64();
            break;
          }
          case 34: {
            UserId = input.ReadString();
            break;
          }
          case 42: {
            questions_.AddEntriesFrom(input, _repeated_questions_codec);
            break;
          }
          case 50: {
            if (topic_ == null) {
              Topic = new global::Shared.Contracts.QuizManagement.Quizzes.TopicResult();
            }
            input.ReadMessage(Topic);
            break;
          }
          case 56: {
            IsPublic = input.ReadBool();
            break;
          }
          case 66: {
            ImageUrl = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetQuizzesPagedResult : pb::IMessage<GetQuizzesPagedResult> {
    private static readonly pb::MessageParser<GetQuizzesPagedResult> _parser = new pb::MessageParser<GetQuizzesPagedResult>(() => new GetQuizzesPagedResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetQuizzesPagedResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizzesPagedResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizzesPagedResult(GetQuizzesPagedResult other) : this() {
      pageInfo_ = other.pageInfo_ != null ? other.pageInfo_.Clone() : null;
      quizzes_ = other.quizzes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuizzesPagedResult Clone() {
      return new GetQuizzesPagedResult(this);
    }

    /// <summary>Field number for the "PageInfo" field.</summary>
    public const int PageInfoFieldNumber = 1;
    private global::Shared.Contracts.Common.GetPagedResult pageInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Shared.Contracts.Common.GetPagedResult PageInfo {
      get { return pageInfo_; }
      set {
        pageInfo_ = value;
      }
    }

    /// <summary>Field number for the "Quizzes" field.</summary>
    public const int QuizzesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Shared.Contracts.QuizManagement.Quizzes.QuizResult> _repeated_quizzes_codec
        = pb::FieldCodec.ForMessage(18, global::Shared.Contracts.QuizManagement.Quizzes.QuizResult.Parser);
    private readonly pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.QuizResult> quizzes_ = new pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.QuizResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.QuizResult> Quizzes {
      get { return quizzes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetQuizzesPagedResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetQuizzesPagedResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PageInfo, other.PageInfo)) return false;
      if(!quizzes_.Equals(other.quizzes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (pageInfo_ != null) hash ^= PageInfo.GetHashCode();
      hash ^= quizzes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (pageInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PageInfo);
      }
      quizzes_.WriteTo(output, _repeated_quizzes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (pageInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PageInfo);
      }
      size += quizzes_.CalculateSize(_repeated_quizzes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetQuizzesPagedResult other) {
      if (other == null) {
        return;
      }
      if (other.pageInfo_ != null) {
        if (pageInfo_ == null) {
          PageInfo = new global::Shared.Contracts.Common.GetPagedResult();
        }
        PageInfo.MergeFrom(other.PageInfo);
      }
      quizzes_.Add(other.quizzes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pageInfo_ == null) {
              PageInfo = new global::Shared.Contracts.Common.GetPagedResult();
            }
            input.ReadMessage(PageInfo);
            break;
          }
          case 18: {
            quizzes_.AddEntriesFrom(input, _repeated_quizzes_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Result DTOs
  /// </summary>
  public sealed partial class AnswerResult : pb::IMessage<AnswerResult> {
    private static readonly pb::MessageParser<AnswerResult> _parser = new pb::MessageParser<AnswerResult>(() => new AnswerResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AnswerResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnswerResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnswerResult(AnswerResult other) : this() {
      answerId_ = other.answerId_;
      text_ = other.text_;
      isCorrect_ = other.isCorrect_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnswerResult Clone() {
      return new AnswerResult(this);
    }

    /// <summary>Field number for the "AnswerId" field.</summary>
    public const int AnswerIdFieldNumber = 1;
    private int answerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AnswerId {
      get { return answerId_; }
      set {
        answerId_ = value;
      }
    }

    /// <summary>Field number for the "Text" field.</summary>
    public const int TextFieldNumber = 2;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IsCorrect" field.</summary>
    public const int IsCorrectFieldNumber = 3;
    private bool isCorrect_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsCorrect {
      get { return isCorrect_; }
      set {
        isCorrect_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AnswerResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AnswerResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AnswerId != other.AnswerId) return false;
      if (Text != other.Text) return false;
      if (IsCorrect != other.IsCorrect) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AnswerId != 0) hash ^= AnswerId.GetHashCode();
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (IsCorrect != false) hash ^= IsCorrect.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AnswerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AnswerId);
      }
      if (Text.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Text);
      }
      if (IsCorrect != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsCorrect);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AnswerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AnswerId);
      }
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (IsCorrect != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AnswerResult other) {
      if (other == null) {
        return;
      }
      if (other.AnswerId != 0) {
        AnswerId = other.AnswerId;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      if (other.IsCorrect != false) {
        IsCorrect = other.IsCorrect;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AnswerId = input.ReadInt32();
            break;
          }
          case 18: {
            Text = input.ReadString();
            break;
          }
          case 24: {
            IsCorrect = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class QuestionResult : pb::IMessage<QuestionResult> {
    private static readonly pb::MessageParser<QuestionResult> _parser = new pb::MessageParser<QuestionResult>(() => new QuestionResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuestionResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuestionResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuestionResult(QuestionResult other) : this() {
      questionId_ = other.questionId_;
      text_ = other.text_;
      isMultipleChoice_ = other.isMultipleChoice_;
      answers_ = other.answers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuestionResult Clone() {
      return new QuestionResult(this);
    }

    /// <summary>Field number for the "QuestionId" field.</summary>
    public const int QuestionIdFieldNumber = 1;
    private int questionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int QuestionId {
      get { return questionId_; }
      set {
        questionId_ = value;
      }
    }

    /// <summary>Field number for the "Text" field.</summary>
    public const int TextFieldNumber = 2;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IsMultipleChoice" field.</summary>
    public const int IsMultipleChoiceFieldNumber = 3;
    private bool isMultipleChoice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsMultipleChoice {
      get { return isMultipleChoice_; }
      set {
        isMultipleChoice_ = value;
      }
    }

    /// <summary>Field number for the "Answers" field.</summary>
    public const int AnswersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Shared.Contracts.QuizManagement.Quizzes.AnswerResult> _repeated_answers_codec
        = pb::FieldCodec.ForMessage(34, global::Shared.Contracts.QuizManagement.Quizzes.AnswerResult.Parser);
    private readonly pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.AnswerResult> answers_ = new pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.AnswerResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Shared.Contracts.QuizManagement.Quizzes.AnswerResult> Answers {
      get { return answers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuestionResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuestionResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QuestionId != other.QuestionId) return false;
      if (Text != other.Text) return false;
      if (IsMultipleChoice != other.IsMultipleChoice) return false;
      if(!answers_.Equals(other.answers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (QuestionId != 0) hash ^= QuestionId.GetHashCode();
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (IsMultipleChoice != false) hash ^= IsMultipleChoice.GetHashCode();
      hash ^= answers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (QuestionId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QuestionId);
      }
      if (Text.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Text);
      }
      if (IsMultipleChoice != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsMultipleChoice);
      }
      answers_.WriteTo(output, _repeated_answers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (QuestionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuestionId);
      }
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (IsMultipleChoice != false) {
        size += 1 + 1;
      }
      size += answers_.CalculateSize(_repeated_answers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuestionResult other) {
      if (other == null) {
        return;
      }
      if (other.QuestionId != 0) {
        QuestionId = other.QuestionId;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      if (other.IsMultipleChoice != false) {
        IsMultipleChoice = other.IsMultipleChoice;
      }
      answers_.Add(other.answers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            QuestionId = input.ReadInt32();
            break;
          }
          case 18: {
            Text = input.ReadString();
            break;
          }
          case 24: {
            IsMultipleChoice = input.ReadBool();
            break;
          }
          case 34: {
            answers_.AddEntriesFrom(input, _repeated_answers_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class QuizResult : pb::IMessage<QuizResult> {
    private static readonly pb::MessageParser<QuizResult> _parser = new pb::MessageParser<QuizResult>(() => new QuizResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuizResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizResult(QuizResult other) : this() {
      quizId_ = other.quizId_;
      name_ = other.name_;
      creationTimestamp_ = other.creationTimestamp_;
      userId_ = other.userId_;
      topic_ = other.topic_ != null ? other.topic_.Clone() : null;
      isPublic_ = other.isPublic_;
      imageUrl_ = other.imageUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuizResult Clone() {
      return new QuizResult(this);
    }

    /// <summary>Field number for the "QuizId" field.</summary>
    public const int QuizIdFieldNumber = 1;
    private int quizId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int QuizId {
      get { return quizId_; }
      set {
        quizId_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CreationTimestamp" field.</summary>
    public const int CreationTimestampFieldNumber = 3;
    private long creationTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CreationTimestamp {
      get { return creationTimestamp_; }
      set {
        creationTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "UserId" field.</summary>
    public const int UserIdFieldNumber = 4;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Topic" field.</summary>
    public const int TopicFieldNumber = 5;
    private global::Shared.Contracts.QuizManagement.Quizzes.TopicResult topic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Shared.Contracts.QuizManagement.Quizzes.TopicResult Topic {
      get { return topic_; }
      set {
        topic_ = value;
      }
    }

    /// <summary>Field number for the "IsPublic" field.</summary>
    public const int IsPublicFieldNumber = 6;
    private bool isPublic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsPublic {
      get { return isPublic_; }
      set {
        isPublic_ = value;
      }
    }

    /// <summary>Field number for the "ImageUrl" field.</summary>
    public const int ImageUrlFieldNumber = 7;
    private string imageUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ImageUrl {
      get { return imageUrl_; }
      set {
        imageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuizResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuizResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QuizId != other.QuizId) return false;
      if (Name != other.Name) return false;
      if (CreationTimestamp != other.CreationTimestamp) return false;
      if (UserId != other.UserId) return false;
      if (!object.Equals(Topic, other.Topic)) return false;
      if (IsPublic != other.IsPublic) return false;
      if (ImageUrl != other.ImageUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (QuizId != 0) hash ^= QuizId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (CreationTimestamp != 0L) hash ^= CreationTimestamp.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (topic_ != null) hash ^= Topic.GetHashCode();
      if (IsPublic != false) hash ^= IsPublic.GetHashCode();
      if (ImageUrl.Length != 0) hash ^= ImageUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (QuizId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QuizId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (CreationTimestamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CreationTimestamp);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UserId);
      }
      if (topic_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Topic);
      }
      if (IsPublic != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsPublic);
      }
      if (ImageUrl.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ImageUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (QuizId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuizId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (CreationTimestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreationTimestamp);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (topic_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Topic);
      }
      if (IsPublic != false) {
        size += 1 + 1;
      }
      if (ImageUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuizResult other) {
      if (other == null) {
        return;
      }
      if (other.QuizId != 0) {
        QuizId = other.QuizId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.CreationTimestamp != 0L) {
        CreationTimestamp = other.CreationTimestamp;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.topic_ != null) {
        if (topic_ == null) {
          Topic = new global::Shared.Contracts.QuizManagement.Quizzes.TopicResult();
        }
        Topic.MergeFrom(other.Topic);
      }
      if (other.IsPublic != false) {
        IsPublic = other.IsPublic;
      }
      if (other.ImageUrl.Length != 0) {
        ImageUrl = other.ImageUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            QuizId = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            CreationTimestamp = input.ReadInt64();
            break;
          }
          case 34: {
            UserId = input.ReadString();
            break;
          }
          case 42: {
            if (topic_ == null) {
              Topic = new global::Shared.Contracts.QuizManagement.Quizzes.TopicResult();
            }
            input.ReadMessage(Topic);
            break;
          }
          case 48: {
            IsPublic = input.ReadBool();
            break;
          }
          case 58: {
            ImageUrl = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class TopicResult : pb::IMessage<TopicResult> {
    private static readonly pb::MessageParser<TopicResult> _parser = new pb::MessageParser<TopicResult>(() => new TopicResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TopicResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TopicResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TopicResult(TopicResult other) : this() {
      topicId_ = other.topicId_;
      name_ = other.name_;
      imageUrl_ = other.imageUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TopicResult Clone() {
      return new TopicResult(this);
    }

    /// <summary>Field number for the "TopicId" field.</summary>
    public const int TopicIdFieldNumber = 1;
    private int topicId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TopicId {
      get { return topicId_; }
      set {
        topicId_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ImageUrl" field.</summary>
    public const int ImageUrlFieldNumber = 3;
    private string imageUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ImageUrl {
      get { return imageUrl_; }
      set {
        imageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TopicResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TopicResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TopicId != other.TopicId) return false;
      if (Name != other.Name) return false;
      if (ImageUrl != other.ImageUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TopicId != 0) hash ^= TopicId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (ImageUrl.Length != 0) hash ^= ImageUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TopicId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TopicId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (ImageUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ImageUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TopicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopicId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (ImageUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TopicResult other) {
      if (other == null) {
        return;
      }
      if (other.TopicId != 0) {
        TopicId = other.TopicId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.ImageUrl.Length != 0) {
        ImageUrl = other.ImageUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TopicId = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            ImageUrl = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
