// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QuizManagement/Quizzes.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Shared.Contracts.QuizManagement.Quizzes {
  public static partial class QuizzesService
  {
    static readonly string __ServiceName = "Shared.Contracts.QuizManagement.Quizzes.QuizzesService";

    static readonly grpc::Marshaller<global::Shared.Contracts.Common.GetPagedParameter> __Marshaller_Shared_Contracts_Common_GetPagedParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.Common.GetPagedParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesPagedResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter> __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizByIdParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult> __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizByIdResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter> __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesByUserPagedParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter> __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesByTopicPagedParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter> __Marshaller_Shared_Contracts_QuizManagement_Quizzes_CreateQuizParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.Common.Empty> __Marshaller_Shared_Contracts_Common_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.Common.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter> __Marshaller_Shared_Contracts_QuizManagement_Quizzes_DeleteQuizParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter> __Marshaller_Shared_Contracts_QuizManagement_Quizzes_DeleteQuizzesByUserParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter.Parser.ParseFrom);

    static readonly grpc::Method<global::Shared.Contracts.Common.GetPagedParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> __Method_GetQuizzesPaged = new grpc::Method<global::Shared.Contracts.Common.GetPagedParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetQuizzesPaged",
        __Marshaller_Shared_Contracts_Common_GetPagedParameter,
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesPagedResult);

    static readonly grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult> __Method_GetQuiz = new grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetQuiz",
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizByIdParameter,
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizByIdResult);

    static readonly grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> __Method_GetQuizzesByUserPaged = new grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetQuizzesByUserPaged",
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesByUserPagedParameter,
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesPagedResult);

    static readonly grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> __Method_GetPublicQuizzesByUserPaged = new grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPublicQuizzesByUserPaged",
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesByUserPagedParameter,
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesPagedResult);

    static readonly grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> __Method_GetQuizzesByTopicPaged = new grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter, global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetQuizzesByTopicPaged",
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesByTopicPagedParameter,
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_GetQuizzesPagedResult);

    static readonly grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter, global::Shared.Contracts.Common.Empty> __Method_CreateQuiz = new grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter, global::Shared.Contracts.Common.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateQuiz",
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_CreateQuizParameter,
        __Marshaller_Shared_Contracts_Common_Empty);

    static readonly grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter, global::Shared.Contracts.Common.Empty> __Method_DeleteQuiz = new grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter, global::Shared.Contracts.Common.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteQuiz",
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_DeleteQuizParameter,
        __Marshaller_Shared_Contracts_Common_Empty);

    static readonly grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter, global::Shared.Contracts.Common.Empty> __Method_DeleteQuizzesByUser = new grpc::Method<global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter, global::Shared.Contracts.Common.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteQuizzesByUser",
        __Marshaller_Shared_Contracts_QuizManagement_Quizzes_DeleteQuizzesByUserParameter,
        __Marshaller_Shared_Contracts_Common_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Shared.Contracts.QuizManagement.Quizzes.QuizzesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of QuizzesService</summary>
    public abstract partial class QuizzesServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetQuizzesPaged(global::Shared.Contracts.Common.GetPagedParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult> GetQuiz(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetQuizzesByUserPaged(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetPublicQuizzesByUserPaged(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetQuizzesByTopicPaged(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.Common.Empty> CreateQuiz(global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.Common.Empty> DeleteQuiz(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.Common.Empty> DeleteQuizzesByUser(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for QuizzesService</summary>
    public partial class QuizzesServiceClient : grpc::ClientBase<QuizzesServiceClient>
    {
      /// <summary>Creates a new client for QuizzesService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public QuizzesServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for QuizzesService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public QuizzesServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected QuizzesServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected QuizzesServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult GetQuizzesPaged(global::Shared.Contracts.Common.GetPagedParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuizzesPaged(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult GetQuizzesPaged(global::Shared.Contracts.Common.GetPagedParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetQuizzesPaged, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetQuizzesPagedAsync(global::Shared.Contracts.Common.GetPagedParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuizzesPagedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetQuizzesPagedAsync(global::Shared.Contracts.Common.GetPagedParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetQuizzesPaged, null, options, request);
      }
      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult GetQuiz(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuiz(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult GetQuiz(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetQuiz, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult> GetQuizAsync(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuizAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdResult> GetQuizAsync(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizByIdParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetQuiz, null, options, request);
      }
      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult GetQuizzesByUserPaged(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuizzesByUserPaged(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult GetQuizzesByUserPaged(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetQuizzesByUserPaged, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetQuizzesByUserPagedAsync(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuizzesByUserPagedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetQuizzesByUserPagedAsync(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetQuizzesByUserPaged, null, options, request);
      }
      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult GetPublicQuizzesByUserPaged(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPublicQuizzesByUserPaged(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult GetPublicQuizzesByUserPaged(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPublicQuizzesByUserPaged, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetPublicQuizzesByUserPagedAsync(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPublicQuizzesByUserPagedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetPublicQuizzesByUserPagedAsync(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByUserPagedParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPublicQuizzesByUserPaged, null, options, request);
      }
      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult GetQuizzesByTopicPaged(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuizzesByTopicPaged(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult GetQuizzesByTopicPaged(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetQuizzesByTopicPaged, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetQuizzesByTopicPagedAsync(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuizzesByTopicPagedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesPagedResult> GetQuizzesByTopicPagedAsync(global::Shared.Contracts.QuizManagement.Quizzes.GetQuizzesByTopicPagedParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetQuizzesByTopicPaged, null, options, request);
      }
      public virtual global::Shared.Contracts.Common.Empty CreateQuiz(global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateQuiz(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.Common.Empty CreateQuiz(global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateQuiz, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.Common.Empty> CreateQuizAsync(global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateQuizAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.Common.Empty> CreateQuizAsync(global::Shared.Contracts.QuizManagement.Quizzes.CreateQuizParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateQuiz, null, options, request);
      }
      public virtual global::Shared.Contracts.Common.Empty DeleteQuiz(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteQuiz(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.Common.Empty DeleteQuiz(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteQuiz, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.Common.Empty> DeleteQuizAsync(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteQuizAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.Common.Empty> DeleteQuizAsync(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteQuiz, null, options, request);
      }
      public virtual global::Shared.Contracts.Common.Empty DeleteQuizzesByUser(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteQuizzesByUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.Common.Empty DeleteQuizzesByUser(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteQuizzesByUser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.Common.Empty> DeleteQuizzesByUserAsync(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteQuizzesByUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.Common.Empty> DeleteQuizzesByUserAsync(global::Shared.Contracts.QuizManagement.Quizzes.DeleteQuizzesByUserParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteQuizzesByUser, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override QuizzesServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new QuizzesServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(QuizzesServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetQuizzesPaged, serviceImpl.GetQuizzesPaged)
          .AddMethod(__Method_GetQuiz, serviceImpl.GetQuiz)
          .AddMethod(__Method_GetQuizzesByUserPaged, serviceImpl.GetQuizzesByUserPaged)
          .AddMethod(__Method_GetPublicQuizzesByUserPaged, serviceImpl.GetPublicQuizzesByUserPaged)
          .AddMethod(__Method_GetQuizzesByTopicPaged, serviceImpl.GetQuizzesByTopicPaged)
          .AddMethod(__Method_CreateQuiz, serviceImpl.CreateQuiz)
          .AddMethod(__Method_DeleteQuiz, serviceImpl.DeleteQuiz)
          .AddMethod(__Method_DeleteQuizzesByUser, serviceImpl.DeleteQuizzesByUser).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, QuizzesServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetQuizzesPaged, serviceImpl.GetQuizzesPaged);
      serviceBinder.AddMethod(__Method_GetQuiz, serviceImpl.GetQuiz);
      serviceBinder.AddMethod(__Method_GetQuizzesByUserPaged, serviceImpl.GetQuizzesByUserPaged);
      serviceBinder.AddMethod(__Method_GetPublicQuizzesByUserPaged, serviceImpl.GetPublicQuizzesByUserPaged);
      serviceBinder.AddMethod(__Method_GetQuizzesByTopicPaged, serviceImpl.GetQuizzesByTopicPaged);
      serviceBinder.AddMethod(__Method_CreateQuiz, serviceImpl.CreateQuiz);
      serviceBinder.AddMethod(__Method_DeleteQuiz, serviceImpl.DeleteQuiz);
      serviceBinder.AddMethod(__Method_DeleteQuizzesByUser, serviceImpl.DeleteQuizzesByUser);
    }

  }
}
#endregion
