// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QuizManagement/Topics.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Shared.Contracts.QuizManagement.Topics {
  public static partial class TopicsService
  {
    static readonly string __ServiceName = "Shared.Contracts.QuizManagement.Topics.TopicsService";

    static readonly grpc::Marshaller<global::Shared.Contracts.Common.Empty> __Marshaller_Shared_Contracts_Common_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.Common.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Topics.GetAllTopicsResult> __Marshaller_Shared_Contracts_QuizManagement_Topics_GetAllTopicsResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Topics.GetAllTopicsResult.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdParameter> __Marshaller_Shared_Contracts_QuizManagement_Topics_GetTopicByIdParameter = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdParameter.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdResult> __Marshaller_Shared_Contracts_QuizManagement_Topics_GetTopicByIdResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdResult.Parser.ParseFrom);

    static readonly grpc::Method<global::Shared.Contracts.Common.Empty, global::Shared.Contracts.QuizManagement.Topics.GetAllTopicsResult> __Method_GetAllTopics = new grpc::Method<global::Shared.Contracts.Common.Empty, global::Shared.Contracts.QuizManagement.Topics.GetAllTopicsResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllTopics",
        __Marshaller_Shared_Contracts_Common_Empty,
        __Marshaller_Shared_Contracts_QuizManagement_Topics_GetAllTopicsResult);

    static readonly grpc::Method<global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdParameter, global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdResult> __Method_GetTopicById = new grpc::Method<global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdParameter, global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTopicById",
        __Marshaller_Shared_Contracts_QuizManagement_Topics_GetTopicByIdParameter,
        __Marshaller_Shared_Contracts_QuizManagement_Topics_GetTopicByIdResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Shared.Contracts.QuizManagement.Topics.TopicsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TopicsService</summary>
    public abstract partial class TopicsServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.QuizManagement.Topics.GetAllTopicsResult> GetAllTopics(global::Shared.Contracts.Common.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdResult> GetTopicById(global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdParameter request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TopicsService</summary>
    public partial class TopicsServiceClient : grpc::ClientBase<TopicsServiceClient>
    {
      /// <summary>Creates a new client for TopicsService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TopicsServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TopicsService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TopicsServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TopicsServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TopicsServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Shared.Contracts.QuizManagement.Topics.GetAllTopicsResult GetAllTopics(global::Shared.Contracts.Common.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllTopics(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.QuizManagement.Topics.GetAllTopicsResult GetAllTopics(global::Shared.Contracts.Common.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllTopics, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Topics.GetAllTopicsResult> GetAllTopicsAsync(global::Shared.Contracts.Common.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllTopicsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Topics.GetAllTopicsResult> GetAllTopicsAsync(global::Shared.Contracts.Common.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllTopics, null, options, request);
      }
      public virtual global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdResult GetTopicById(global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTopicById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdResult GetTopicById(global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdParameter request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTopicById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdResult> GetTopicByIdAsync(global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdParameter request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTopicByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdResult> GetTopicByIdAsync(global::Shared.Contracts.QuizManagement.Topics.GetTopicByIdParameter request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTopicById, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TopicsServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TopicsServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TopicsServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllTopics, serviceImpl.GetAllTopics)
          .AddMethod(__Method_GetTopicById, serviceImpl.GetTopicById).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TopicsServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllTopics, serviceImpl.GetAllTopics);
      serviceBinder.AddMethod(__Method_GetTopicById, serviceImpl.GetTopicById);
    }

  }
}
#endregion
