const ActionTypes = {
    REGISTERING_USER: 'REGISTERING_USER',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
    LOGGING_IN: 'LOGGING_IN',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_IN_ERROR: 'LOG_IN_ERROR'
};

export default ActionTypes;